server:
  port: 9003

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: qzr-producer
