server:
  port: 9005
spring:
  application:
    name: qzr-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TonyRanGee/CloudConfig/cloud-repo
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka